import React from 'react'
import Head from 'next/head'
import { gql } from "@apollo/client";
import client from "../apollo-client";
import Form from '../components/Form'

export default function Home({ posts }) {
  const [showModal, setShowModal] = React.useState(false);
  console.log('posts', posts)
  return (
    <div>
      <Head>
        <title>Test App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main>
      <button
        className="inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"
        type="button"
        onClick={() => setShowModal(true)}
      >
       Add Item
      </button>
      {showModal ? (
        <>
          <div
            className="justify-center items-center flex overflow-x-hidden overflow-y-auto fixed inset-0 z-50 outline-none focus:outline-none"
          >
            <div className="relative w-auto my-6 mx-auto max-w-3xl">
              {/*content*/}
              <div className="border-0 rounded-lg shadow-lg relative flex flex-col w-full bg-white outline-none focus:outline-none">
                {/*header*/}
                <div className="flex items-start justify-between p-5 border-b border-solid border-blueGray-200 rounded-t">
                  <h3 className="text-3xl font-semibold">
                   Add Item
                  </h3>
                  <button
                    className="text-red-500 background-transparent font-bold uppercase px-6 py-2 text-sm outline-none focus:outline-none mr-1 mb-1 ease-linear transition-all duration-150"
                    type="button"
                    onClick={() => setShowModal(false)}
                  >
                    Close
                  </button>
                  <button
                    className="p-1 ml-auto bg-transparent border-0 text-black opacity-5 float-right text-3xl leading-none font-semibold outline-none focus:outline-none"
                    onClick={() => setShowModal(false)}
                  >
                    <span className="bg-transparent text-black opacity-5 h-6 w-6 text-2xl block outline-none focus:outline-none">
                      ×
                    </span>
                  </button>
                </div>
                {/*body*/}
                <div className="relative p-6 flex-auto">
                  <p className="my-4 text-blueGray-500 text-lg leading-relaxed">
                    <Form showModal={setShowModal}/>
                  </p>
                </div>
                {/*footer*/}
                
              </div>
            </div>
          </div>
          <div className="opacity-25 fixed inset-0 z-40 bg-black"></div>
        </>
      ) : null}
      <table className="table-auto">
          <thead>
            <tr>
              <th>Name</th>
              <th>Bio</th>
              <th>Photo</th>
            </tr>
          </thead>
          <tbody>
          {posts.map(post => (
            <tr key={post.id} className=" p-100 border-b border-solid border-blueGray-200 rounded-t">
              <td>{post.name}</td>
              <td>{post.bio}</td>
              <td>{post.status}</td>
              <td> {post?.photo  && <img style={{"height" : "50%", "width": "30%"}} src={`${post?.photo[0]?.url}`}></img>}</td>
            </tr>
          ))}
          </tbody>
        </table>
       
      </main>
    </div>
  )
}


export async function getStaticProps() {
  const { data } = await client.query({
    query: gql`
      query GetData {
        pulp {
          bio
          id
          name
          photo
        }
      }
    
    `,
  });

  return {
    props: {
      posts: data.pulp,
    },
 };
}